baseURL: "https://sorasuegami.github.io/Garbling-LLC/"
languageCode: "ja"
title: "合同会社Garbling"
theme: hugo-profile
canonifyURLs: true

# outputs:
#   home:
#     - "HTML"
#     - "RSS"
#     - "JSON"
#   page:
#     - "HTML"
#     - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "合同会社Garbling"
  description: 合同会社Garbling
  staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: true

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "合同会社Garbling" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: ""
    title: "合同会社Garbling"
    subtitle: "Garbling LLC"
    content: "高機能暗号で、システムの安全性とデータのプライバシーを守ります。"
    image: /fav.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/SoraSuegami
        # - icon: fab fa-x-twitter
        #   url: https://example.com
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "Garblingの役割"
    image: "about.png"
    content: |-
      今後より多くの場面で、資産や生命、機密情報を扱う業務がシステム、特にAIによって自動化されます。そこで課題になるのが、システムの安全性とデータのプライバシーです。これらを保護するために、合同会社Garblingは高機能暗号技術を用いたソリューションを提供します。
    
    skills:
      enable: true
      title: "以下の分野で研究開発を行なっています。"
      items:
        - "ゼロ知識証明"
        - "秘密計算"
        - "ブロックチェーン"
        - "AIセキュリティ"


      # - job: "Junior Software Developer"
      #   company: "Apple"
      #   companyUrl: "https://example.com"
      #   date: "Jan 2020 - Aug 2020"
      #   info:
      #     enable: false
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "UI/UX Designer"
      #   company: "Netflix"
      #   companyUrl: "https://example.com"
      #   date: "June 2017 - Nov 2019"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "Product Designer"
      #   company: "Google"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  education:
    enable: true
    title: "研究開発実績"
    index: false
    items:
      - title: "Cryptographic obfuscation for smart contracts: Trustless bitcoin bridge and more."
        school:
          name: "Suegami, S."
        date: "2022"
        featuredLink:
          enable: true
          url: "https://doi.org/10.1016/j.bcra.2022.100118"
        content: |-
          Blockchain: Research and Applications, 100118.
      - title: "Contract Wallet Using Emails."
        school:
          name: "Suegami, S., & Shibano, K."
        date: "2023, May"
        featuredLink:
          enable: true
          url: "https://arxiv.org/pdf/2312.04173.pdf"
        content: |-
          In 2023 IEEE International Conference on Blockchain and Cryptocurrency (ICBC) (pp. 1-2). IEEE.
      - title: "Self-Examination Mechanism: 説明可能 AI を用いた敵対的攻撃に対する軽量な防御機構."
        school:
          name: "末神奏宙, 小栗悠太郎, 趙在瀛, 加賀谷湧, 向井皇喜, 吉田舜, & 山崎俊彦."
        date: "2023"
        featuredLink:
          enable: true
          url: "https://www.jstage.jst.go.jp/article/pjsai/JSAI2023/0/JSAI2023_2A1GS203/_pdf/-char/ja"
        content: |-
          In 人工 知能学会全国大会論文集 第 37 回 (2023) (pp. 2A1GS203-2A1GS203). 一般社団法人 人工知能学会.
      - title: "Octopus Contract and its Applications."
        school:
          name: "Suegami, S., & Hioki, L."
        date: "2023, Dec"
        featuredLink:
          enable: true
          url: "https://github.com/SoraSuegami/octopus-contract-paper/blob/11ce8419a831c5db901ba9670af50335ae1e0865/octopus_contract_swe_1215.pdf"
        content: |-

      - title: "Self-Examination Mechanism: Improving Standard Accuracy in Adversarial Purification."
        school:
          name: "Suegami, S., Oguri, Y., Zhao, Z., Kagaya, Y., and Yamasaki, T."
        date: "2024"
        # featuredLink:
          # enable: true
          # url: "https://doi.org/10.1016/j.bcra.2022.100118"
        content: |-
          IVSP 2024.

      - title: "ZK Email: On-chain verification of emails using ZKP."
        date: "2023, Sep"
        featuredLink:
          enable: true
          url: "https://speakerdeck.com/sorasuegami/ethcon-korea-2023-zk-email-on-chain-verification-of-emails-using-zkp"
        content: |-
          Ethcon 2023 in Seoul, Korea.

      - title: "ZK Email: Email Wallet and Identity Attestations."
        date: "2023, Nov"
        featuredLink:
          enable: true
          url: "https://www.youtube.com/watch?v=qUYBja0glio&list=PL-ZQkds07L_oJA72_JCXK7_OnSNTevOks&index=27"
        content: |-
           Progcrypto in Istanbul, Turkey.

      - title: "Grant for the development of RSA verification circuit in halo2 from Ethereum Foundation."
        date: "2022"
        featuredLink:
          enable: true
          url: "https://blog.ethereum.org/2022/12/07/esp-allocation-q3-22"
      
      - title: "Grant for the development of ZKEmail from Ethereum Foundation."
        date: "2023"
        featuredLink:
          enable: true
          url: "https://blog.ethereum.org/2023/08/15/allocation-update-q2-23"
      
      - title: "Grant for the development of Email Wallet from Ethereum Foundation."
        date: "2023"
        featuredLink:
          enable: true
          url: "https://blog.ethereum.org/2024/02/20/esp-allocation-q423 "

      

  # Achievements
  # achievements:
  #   enable: true
  #   title: "研究開発実績"
  #   items:
  #     - title: "Suegami, S. (2022). Cryptographic obfuscation for smart contracts: Trustless bitcoin bridge and more. Blockchain: Research and Applications, 100118."
  #       content: I solved all problems with optimal solution.
  #       url: https://doi.org/10.1016/j.bcra.2022.100118
  #       # image: /images/achievment.jpg
  #     - title: "Suegami, S., & Shibano, K. (2023, May). Contract Wallet Using Emails. In 2023 IEEE International Conference on Blockchain and Cryptocurrency (ICBC) (pp. 1-2). IEEE."
  #       content: Developed a product using Artificial Intelligence.
  #       url: https://arxiv.org/pdf/2312.04173.pdf
  #       # image: /images/achievment.jpg
  #     - title: "末神奏宙, 小栗悠太郎, 趙在瀛, 加賀谷湧, 向井皇喜, 吉田舜, & 山崎俊彦. (2023). Self-Examination Mechanism: 説明可能 AI を用いた敵対的攻撃に対する軽量な防御機構. In 人工 知能学会全国大会論文集 第 37 回 (2023) (pp. 2A1GS203-2A1GS203). 一般社団法人 人工知能学会."
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://www.jstage.jst.go.jp/article/pjsai/JSAI2023/0/JSAI2023_2A1GS203/_pdf/-char/ja"
  #       # image: /images/achievment.jpg
  #     - title: "Suegami, S., & Hioki, L. (2023, Dec). Octopus Contract and its Applications."
  #       content: We are developed a product which can help others.
  #       url: "https://github.com/SoraSuegami/octopus-contract-paper/blob/11ce8419a831c5db901ba9670af50335ae1e0865/octopus_contract_swe_1215.pdf"
  #     - title: "Suegami, S., Oguri, Y., Zhao, Z., Kagaya, Y., Mukai, K., Yoshida, S., Chen F., and Yamasaki, T., Self-Examination Mechanism: Improving Standard Accuracy in Adversarial Purification, IVSP 2024."
  #       content: We are developed a product which can help others.
  # projects
  # projects:
  #   enable: true
  #   title: "研究開発実績"
  #   items:
  #     - title: Hugo Profile
  #       content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        # image: /images/projects/profile.png
        # featured:
        #   name: Demo
        #   link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        # links:
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      # - title: Image Converter
      #   content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
      #   image: /images/projects/converter.jpg
      #   featured:
      #     name: Demo
      #     link: https://django-converter.herokuapp.com
      #   badges:
      #     - "Django"
      #     - "Bootstrap"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/converter

      # - title: Hugo Profile V2
      #   content: A clean and simple Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile2.jpg
      #   featured:
      #     name: Demo V2
      #     link: https://hugo-profile-2.netlify.app
      #   badges:
      #     - "Hugo"
      #     - "Bootstrap"
      #     - "Javascript"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    title: "連絡先"
    content: |
      代表社員: 末神奏宙

      住所: 〒1040061 東京都中央区銀座7丁目13番21号 銀座sinrokusyuビル2階

      メールアドレス: suegamisora@gmail.com

    btnName: メールを送信
    btnLink: mailto:suegamisora@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    # socialNetworks:
    #   github: https://github.com
    #   linkedin: https://linkedin.com
    #   twitter: https://twitter.com
    #   instagram: https://instagram.com
    #   facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "ページが見つかりません。"
    # emailText: "Check out this site"

  # datesFormat:
  #   article: "Jan 2, 2006"
  #   articleList: "Jan 2, 2006"
  #   articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>